-- Create test unclaimed businesses for claim flow testing
-- Run this AFTER running add_contact_columns_to_business_profiles.sql
-- Simulates businesses imported from Google Places API with COMPLETE data

-- IMPORTANT: Replace YOUR_ADMIN_USER_ID with your actual admin user ID
-- To find it, run: SELECT id FROM auth.users WHERE email = 'your-admin-email@example.com';

INSERT INTO business_profiles (
  id,
  user_id,
  business_name,
  business_address,
  business_town,
  business_postcode,
  business_type,
  business_category,
  business_tagline,
  phone,
  email,
  website,
  business_images,
  rating,
  review_count,
  years_on_google,
  city,
  status,
  visibility,
  auto_imported,
  google_place_id,
  created_at
) VALUES
  (
    gen_random_uuid(),
    NULL, -- Imported businesses have NULL user_id (no creator)
    'The Golden Spoon',
    '45 High Street',
    'Bournemouth',
    'BH1 2AB',
    'Restaurant',
    'Fine Dining',
    'Exquisite British cuisine with a modern twist',
    '01202 555001',
    'info@goldenspoon.co.uk',
    'https://goldenspoon.co.uk',
    ARRAY['https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800'],
    4.6,
    847,
    5,
    'bournemouth',
    'unclaimed',
    'discover_only',
    true,
    'ChIJ_test_golden_spoon',
    NOW()
  ),
  (
    gen_random_uuid(),
    NULL,
    'Coastal Coffee Roasters',
    '78 Beach Road',
    'Bournemouth',
    'BH2 5LT',
    'Cafe',
    'Coffee Shop',
    'Artisan coffee roasted daily on the Dorset coast',
    '01202 555002',
    'hello@coastalcoffee.co.uk',
    'https://coastalcoffee.co.uk',
    ARRAY['https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800'],
    4.8,
    203,
    3,
    'bournemouth',
    'unclaimed',
    'discover_only',
    true,
    'ChIJ_test_coastal_coffee',
    NOW()
  ),
  (
    gen_random_uuid(),
    NULL,
    'The Beachside Bistro',
    '12 Pier Approach',
    'Bournemouth',
    'BH2 5AA',
    'Restaurant',
    'Mediterranean',
    'Fresh seafood and Mediterranean flavours by the sea',
    '01202 555003',
    'bookings@beachsidebistro.co.uk',
    'https://beachsidebistro.co.uk',
    ARRAY['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800'],
    4.5,
    392,
    7,
    'bournemouth',
    'unclaimed',
    'discover_only',
    true,
    'ChIJ_test_beachside_bistro',
    NOW()
  ),
  (
    gen_random_uuid(),
    NULL,
    'Urban Cuts Barbers',
    '34 Commercial Road',
    'Bournemouth',
    'BH2 5LR',
    'Barber',
    'Grooming',
    'Traditional barbering meets modern style',
    '01202 555004',
    'book@urbancuts.co.uk',
    'https://urbancuts.co.uk',
    ARRAY['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800'],
    4.9,
    156,
    4,
    'bournemouth',
    'unclaimed',
    'discover_only',
    true,
    'ChIJ_test_urban_cuts',
    NOW()
  ),
  (
    gen_random_uuid(),
    NULL,
    'The Vine Wine Bar',
    '56 Old Christchurch Road',
    'Bournemouth',
    'BH1 1LR',
    'Bar',
    'Wine Bar',
    'Carefully curated wines from around the world',
    '01202 555005',
    'info@thevinebar.co.uk',
    'https://thevinebar.co.uk',
    ARRAY['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800'],
    4.7,
    521,
    6,
    'bournemouth',
    'unclaimed',
    'discover_only',
    true,
    'ChIJ_test_vine_wine_bar',
    NOW()
  );

-- Verify the businesses were created
SELECT 
  business_name,
  business_category,
  status,
  visibility,
  auto_imported
FROM business_profiles
WHERE status = 'unclaimed'
ORDER BY created_at DESC;
