import { NextRequest, NextResponse } from 'next/server'
import { generateHybridAIResponse } from '@/lib/ai/hybrid-chat'
import { generateQuickReplies, categorizeUserMessage } from '@/lib/ai/chat'
import { getFranchiseCityFromRequest } from '@/lib/utils/franchise-areas'
import { getValidatedUser } from '@/lib/utils/wallet-pass-security'
import { getOpenStatusForToday } from '@/lib/utils/opening-hours'
import { createServiceRoleClient } from '@/lib/supabase/server'

/**
 * Persist user + AI messages to chat_messages table.
 * Awaited before returning the response to prevent Next.js context teardown
 * from killing the in-flight Supabase request. Insert is fast (~50ms).
 */
async function persistChatMessages(
  sessionId: string | undefined,
  walletPassId: string | undefined,
  userMessage: string,
  aiResponse: string,
  metadata?: Record<string, unknown>,
  city?: string
): Promise<void> {
  if (!sessionId || !walletPassId) return

  try {
    const supabase = createServiceRoleClient()
    const now = new Date().toISOString()

    const { error } = await supabase
      .from('chat_messages')
      .insert([
        {
          session_id: sessionId,
          wallet_pass_id: walletPassId,
          role: 'user',
          content: userMessage,
          metadata: {},
          created_at: now,
          ...(city && { city }),
        },
        {
          session_id: sessionId,
          wallet_pass_id: walletPassId,
          role: 'ai',
          content: aiResponse,
          metadata: metadata ?? {},
          created_at: new Date(Date.now() + 1).toISOString(),
          ...(city && { city }),
        },
      ])

    if (error) console.error('[chat-persist] Failed to save messages:', error.message)
  } catch (err) {
    console.error('[chat-persist] Unexpected error:', err)
  }
}

type MentionedBiz = { name: string; slug: string }

function extractMentionedBusinessesFromText(text: string): MentionedBiz[] {
  const matches = [...text.matchAll(/\*\*\[([^\]]+)\]\(\/user\/business\/([a-z0-9-]+)\)\*\*/g)]
  return matches.map(m => ({ name: m[1], slug: m[2] }))
}

/**
 * Infer which business the user is asking about from recent assistant messages
 * Uses markdown links generated by the AI to match business names/tokens to slugs
 */
function inferSelectedBusinessSlugFromHistory(
  message: string,
  conversationHistory: Array<{ role: string; content: string }>
): string | null {
  const msg = (message || '').toLowerCase()

  // Look back over the last few assistant messages for linked businesses
  const recent = [...(conversationHistory || [])]
    .reverse()
    .filter(m => m?.role === 'assistant' && typeof m?.content === 'string')
    .slice(0, 6)

  const mentioned: MentionedBiz[] = []
  for (const m of recent) {
    mentioned.push(...extractMentionedBusinessesFromText(m.content))
    // stop early if we found any in the most recent assistant message
    if (mentioned.length > 0) break
  }

  if (mentioned.length === 0) return null

  // If user message includes a mentioned business name (or a strong token), choose that slug
  // Deterministic: exact substring match on the name (lowercased)
  for (const { name, slug } of mentioned) {
    const n = name.toLowerCase()
    if (n.length >= 4 && msg.includes(n)) return slug
  }

  // Token fallback: if user says "triangle" and we have "Triangle GYROSS"
  // Deterministic: match any word token >= 6 chars from business name that appears in message
  for (const { name, slug } of mentioned) {
    const tokens = name
      .toLowerCase()
      .split(/[^a-z0-9]+/g)
      .filter(t => t.length >= 6)
    if (tokens.some(t => msg.includes(t))) return slug
  }

  // Only return a match if we had actual evidence (name or token match above).
  // Do NOT blindly assume the last-mentioned business — the user might be asking about a different one.
  return null
}

/**
 * Generate slug from business name (matches DB slug generation logic)
 */
function generateSlugFromName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

/**
 * Helper: Auto-inject links for bold business names the AI forgot to link.
 * Builds a name→slug map from all known businesses and replaces **Name** with **[Name](/user/business/slug)**.
 */
function autoInjectBusinessLinks(text: string, businesses: Array<{ business_name?: string; name?: string; slug?: string; id?: string }>): string {
  if (!text || !businesses || businesses.length === 0) return text

  const nameToSlug = new Map<string, string>()
  for (const b of businesses) {
    const name = b.business_name || b.name || ''
    if (!name) continue
    const slug = b.slug || generateSlugFromName(name)
    nameToSlug.set(name.toLowerCase(), slug)
  }

  // Find bold text that is NOT already linked: **Name** but not **[Name](...)** 
  return text.replace(/\*\*([^[*]+?)\*\*/g, (match, name) => {
    const trimmed = name.trim()
    const slug = nameToSlug.get(trimmed.toLowerCase())
    if (slug) {
      return `**[${trimmed}](/user/business/${slug})**`
    }
    return match
  })
}

/**
 * Helper: Force each business link to start a new paragraph
 * MECHANICAL FIX: Handles both linked and unlinked bold business names
 */
function forceNewParagraphPerBusinessLink(text: string): string {
  if (!text) return text

  // Match BOTH formats:
  // 1. Full link: **[Business Name](/user/business/slug)**
  // 2. Plain bold: **Business Name** (when model forgets links)
  const linkRe = /\*\*\[([^\]]+)\]\(\/user\/business\/[a-z0-9-]+\)\*\*/g
  const boldRe = /\*\*([A-Z][^*]{2,}?(?:'s)?[^*]*?)\*\*/g
  
  // First collect all business mentions (linked or not)
  const mentions: Array<{ text: string; index: number }> = []
  
  // Find all linked businesses
  let m: RegExpExecArray | null
  const linkedText = text
  while ((m = linkRe.exec(linkedText)) !== null) {
    mentions.push({ text: m[0], index: m.index })
  }
  
  // Find all bold text that looks like business names (Title Case, reasonable length)
  // But ONLY if we have < 2 linked mentions (fallback mode)
  if (mentions.length < 2) {
    const boldMatches = text.match(boldRe) || []
    // Filter to likely business names: starts with capital, has reasonable words
    const likelyBusinessNames = boldMatches.filter(m => {
      const inner = m.replace(/\*\*/g, '')
      // Business names typically: Title Case, 2-50 chars, not generic phrases
      return inner.length >= 5 && 
             inner.length <= 60 &&
             !/^(The|A|An|Good|Great|Best|Perfect|Love|Want|Curious|Check|Try|Visit)\b/.test(inner)
    })
    
    if (likelyBusinessNames.length >= 2) {
      // Re-scan to get positions
      likelyBusinessNames.forEach(pattern => {
        const idx = text.indexOf(pattern)
        if (idx >= 0 && !mentions.some(m => m.index === idx)) {
          mentions.push({ text: pattern, index: idx })
        }
      })
    }
  }
  
  if (mentions.length < 2) return text.trimEnd()
  
  // Sort by index (earliest first)
  mentions.sort((a, b) => a.index - b.index)
  
  // Insert \n\n before each mention except the first
  let result = text
  let offset = 0
  
  for (let i = 1; i < mentions.length; i++) {
    const mention = mentions[i]
    const insertPos = mention.index + offset
    
    // Check if already has proper spacing
    const before = result.substring(Math.max(0, insertPos - 2), insertPos)
    if (before !== '\n\n') {
      result = result.substring(0, insertPos) + '\n\n' + result.substring(insertPos)
      offset += 2
    }
  }
  
  return result
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()
}

/**
 * Detect "near me" intent from user message
 */
function detectNearMeIntent(message: string): boolean {
  const lowerMessage = message.toLowerCase()
  const nearMePatterns = [
    'near me',
    'close by',
    'nearby',
    'around here',
    'walking distance',
    'close to me',
    'around me',
    'in my area',
    'local to me',
    'closest',
    'nearest'
  ]
  return nearMePatterns.some(pattern => lowerMessage.includes(pattern))
}

/**
 * Detect primary intent from user message
 */
function classifyMessageType(message: string): 'near_me' | 'browse' | 'events' | 'offers' | 'unknown' {
  const lowerMessage = message.toLowerCase()
  
  if (detectNearMeIntent(message)) return 'near_me'
  if (lowerMessage.includes('event') || lowerMessage.includes('happening')) return 'events'
  if (lowerMessage.includes('offer') || lowerMessage.includes('deal') || lowerMessage.includes('discount')) return 'offers'
  if (lowerMessage.includes('find') || lowerMessage.includes('show') || lowerMessage.includes('restaurant') || lowerMessage.includes('bar') || lowerMessage.includes('cafe')) return 'browse'
  
  return 'unknown'
}

/**
 * Generate deterministic quick replies based on context
 */
function generateDeterministicQuickReplies(
  intent: string,
  needsLocation: boolean,
  hasBusinessResults: boolean,
  hasEventCards: boolean
): string[] {
  if (needsLocation) {
    return ["Use my location", "Show city centre instead"]
  }
  
  if (hasBusinessResults) {
    return ["Show me on Atlas", "More like this", "Filter options"]
  }
  
  if (hasEventCards) {
    return ["More events", "This weekend", "Family-friendly"]
  }
  
  // Default suggestions
  if (intent === 'offers') {
    return ["Current deals", "Qwikker Picks", "Near me"]
  }
  
  return ["Find restaurants", "Current deals", "Qwikker Picks"]
}

export async function POST(request: NextRequest) {
  try {
    const { message, walletPassId, conversationHistory, userLocation, sessionId } = await request.json()

    // Validate required fields
    if (!message || typeof message !== 'string') {
      return NextResponse.json(
        { error: 'Message is required and must be a string' },
        { status: 400 }
      )
    }

    // Get franchise city from request
    const city = await getFranchiseCityFromRequest()
    console.log(`🤖 AI Chat request for city: ${city}`)

    // Validate user if wallet pass ID provided
    // CRITICAL: Only pass walletPassId to AI context if validation succeeds
    // Prevents anonymous/stale sessions from leaking other users' loyalty data
    let userName = 'there'
    let validatedWalletPassId: string | undefined = undefined
    if (walletPassId) {
      const { user, isValid } = await getValidatedUser(walletPassId)
      if (isValid && user) {
        userName = user.name || 'there'
        validatedWalletPassId = walletPassId
        console.log(`✅ Validated user: ${userName}`)
      } else {
        console.warn(`⚠️ Invalid wallet pass ID in AI chat — not passing to AI context: ${walletPassId}`)
      }
    }
    
    // Detect intent
    const intent = classifyMessageType(message)
    const isNearMeQuery = intent === 'near_me'
    const hasUserLocation = !!(userLocation?.lat && userLocation?.lng)
    
    console.log(`🎯 Intent: ${intent}, NearMe: ${isNearMeQuery}, HasLocation: ${hasUserLocation}`)
    
    // Near-me queries without location: still return results, but flag that location would help
    const needsLocation = isNearMeQuery && !hasUserLocation
    
    if (needsLocation) {
      console.log('📍 Near-me query without location — will return results sorted by rating, flag for location')
    }

    // 🚀 Generate AI response using HYBRID system (GPT-4o-mini + GPT-4o)
    const result = await generateHybridAIResponse(message, {
      city,
      userName,
      walletPassId: validatedWalletPassId,
      userLocation: hasUserLocation ? {
        latitude: userLocation.lat,
        longitude: userLocation.lng
      } : undefined
    }, conversationHistory || [])

    if (!result.success) {
      console.error('❌ AI response generation failed:', result.error)

      // Detect OpenAI quota exhaustion and alert city admin (throttled to once per hour)
      const isQuotaError = result.error?.includes('insufficient_quota') || result.error?.includes('exceeded your current quota')
      if (isQuotaError) {
        try {
          const now = Date.now()
          const lastAlert = (globalThis as any).__quotaAlertTs || 0
          if (now - lastAlert > 60 * 60 * 1000) {
            (globalThis as any).__quotaAlertTs = now
            const { sendCitySlackNotification } = await import('@/lib/utils/dynamic-notifications')
            await sendCitySlackNotification({
              title: 'OpenAI API Quota Exhausted',
              message: `The OpenAI API key has hit its spending limit. AI chat and knowledge base search are DOWN for all users.\n\nFix: top up credits or raise the spend cap at https://platform.openai.com/settings/organization/billing`,
              city,
              type: 'error'
            })
            console.error('🚨 Slack alert sent: OpenAI quota exhausted')
          }
        } catch (slackErr) {
          console.error('⚠️ Failed to send quota Slack alert:', slackErr)
        }
      }

      // If the error is about missing API key or empty knowledge base, show growth message
      const isConfigurationError = result.error?.includes('not configured') || result.error?.includes('knowledge base')
      
      // Get city display name for personalized message
      const cityDisplayName = city.charAt(0).toUpperCase() + city.slice(1)
      
      return NextResponse.json({
        response: isConfigurationError 
          ? `I'm still getting to know ${cityDisplayName}. As local businesses verify details, I'll be able to recommend specific dishes, offers and hidden spots. For now, explore what's already live in the Discover section and your pass will update automatically.`
          : `I'm still getting to know ${cityDisplayName}. As local businesses verify details, I'll be able to recommend specific dishes, offers and hidden spots. For now, explore what's already live in the Discover section and your pass will update automatically.`,
        intent: 'unknown',
        needsLocation: false,
        showAtlasCta: false,
        sources: [],
        quickReplies: [] // REMOVED: Let users type what they want
      })
    }
    
    // 🗺️ ATLAS CTA LOGIC: Check ACTUAL shown results, not all candidates
    // Only show Atlas CTA if the businesses/pins we're ACTUALLY showing have 2+ valid coords
    const atlasAvailable = result.metadata?.atlasAvailable ?? false
    const coordsCandidateCount = result.metadata?.coordsCandidateCount ?? 0
    
    // Valid-coord helpers — CTA is allowed for a single suggested place
    const hasValidAtlasCoord = (b: any) =>
      b?.latitude &&
      b?.longitude &&
      Math.abs(Number(b.latitude)) <= 90 &&
      Math.abs(Number(b.longitude)) <= 180

    const hasAtlasCarousel = (result.businessCarousel || []).filter(hasValidAtlasCoord).length >= 1
    const hasAtlasPins = (result.mapPins || []).filter(hasValidAtlasCoord).length >= 1
    
    const hasActualBusinessResults = !!(
      (result.businessCarousel && result.businessCarousel.length > 0) ||
      (result.mapPins && result.mapPins.length > 0)
    )
    
    if (process.env.NODE_ENV === 'development') {
      console.log('🗺️ ATLAS CTA CHECK:')
      console.log(`   atlasAvailable (from hybrid-chat): ${atlasAvailable}`)
      console.log(`   coordsCandidateCount: ${coordsCandidateCount}`)
      console.log(`   hasActualBusinessResults: ${hasActualBusinessResults}`)
      console.log(`   hasAtlasCarousel (2+ with coords): ${hasAtlasCarousel}`)
      console.log(`   hasAtlasPins (2+ with coords): ${hasAtlasPins}`)
    }
    
    // Detect specific name queries: "is there a X called/named Y" or "do you have Y"
    // If the user is looking for a specific business by name, only show Atlas if results match
    const specificNameMatch = message.match(/\b(?:called|named|know of|have|find)\s+['"]?([A-Z0-9][\w\s'&-]{1,30})['"]?\s*\??$/i)
      || message.match(/^(?:is there|do you have|know of)\s+(?:a|an|any)\s+\w+\s+(?:called|named)\s+['"]?(.+?)['"]?\s*\??$/i)
    const isSpecificNameQuery = !!specificNameMatch

    let nameMatchSuppressed = false
    if (isSpecificNameQuery && specificNameMatch) {
      const searchedName = specificNameMatch[1].trim().toLowerCase()
      const allResults = [...(result.businessCarousel || []), ...(result.mapPins || [])]
      const hasNameMatch = allResults.some((b: any) =>
        (b.name || b.business_name || '').toLowerCase().includes(searchedName) ||
        searchedName.includes((b.name || b.business_name || '').toLowerCase())
      )
      if (!hasNameMatch) {
        nameMatchSuppressed = true
        if (process.env.NODE_ENV === 'development') {
          console.log(`🗺️ ATLAS CTA SUPPRESSED: User asked for "${searchedName}" but no results match that name`)
        }
      }
    }

    // Show Atlas CTA only if the ACTUAL shown results have 2+ valid coords
    // AND this isn't a specific name query with no matching results
    // AND this isn't a pure event query (no relevant business results to explore)
    const isEventOnlyQuery = intent === 'events' && (result.eventCards?.length || 0) > 0
    let showAtlasCta = atlasAvailable && hasActualBusinessResults && (hasAtlasCarousel || hasAtlasPins) && !nameMatchSuppressed && !isEventOnlyQuery
    
    // 🔧 POST-PROCESS: Remove Atlas mentions from AI response if model mentioned it but UI won't show CTA
    // CRITICAL: Use showAtlasCta (final UI truth), not atlasAvailable (prompt hint)
    let finalResponse = result.response || ''

    // Never pitch "tour these spots" when the reply itself says nothing was found
    const responseSaysNoResults = /\b(couldn'?t find|could not find|can'?t find|cannot find|no places|none of (our|the)|don'?t have any|do not have any|haven'?t found|no (matching )?listings|nothing (matching|serving|listed)|wasn'?t able to find|unable to find)\b/i.test(finalResponse)
    if (showAtlasCta && responseSaysNoResults) {
      showAtlasCta = false
      if (process.env.NODE_ENV === 'development') {
        console.log('🗺️ ATLAS CTA SUPPRESSED: response says no results were found')
      }
    }
    
    // 🎯 DETAIL MODE: Check if this is a detail request about a specific business
    // GUARD: If user is asking for menu items/cocktails/dishes, do NOT enter detail mode
    // Let hybrid AI + KB do extraction (cocktails, dishes, prices, etc)
    const hasSpecificMenuQuery = /\b(cocktail|cocktails|drink|drinks|beer|wine|spirits|menu|food|dishes?|what do they (sell|serve|have|offer)|what('?s| is) on (the )?menu|recommend|best (dish|dishes)|signature|specialt(y|ies))\b/i.test(message)
    
    // Bare venue name / "is X listed?" — detail mode so T1–T3 DB lookup can lock by name.
    // Keep this conservative: require a distinctive token (not pure category phrases).
    const bareNameTrimmed = message.trim().replace(/[\?\!\.]+$/g, '').trim()
    const bareNameWordCount = bareNameTrimmed.split(/\s+/).filter(Boolean).length
    const looksLikeDiscovery =
      /^(show|find|list|where|what|who|how|when|recommend|suggest|any|best|near|all|looking for|i want|i need|are there|is there)\b/i.test(
        bareNameTrimmed
      )
    const bareNameGeneric = new Set([
      'restaurant',
      'restaurants',
      'bar',
      'bars',
      'cafe',
      'cafes',
      'grill',
      'bistro',
      'pub',
      'lounge',
      'house',
      'the',
      'and',
      'club',
      'night',
      'hotel',
      'resort',
      'beach',
      'spa',
      'shop',
      'store',
      'place',
      'spot',
      'food',
      'kitchen',
      'coffee',
      'shops',
      'pizza',
      'sushi',
    ])
    const bareDistinctiveTokens = bareNameTrimmed
      .toLowerCase()
      .replace(/&/g, ' and ')
      .replace(/[^\w\s]/g, ' ')
      .split(/\s+/)
      .filter((t) => t.length >= 2 && !bareNameGeneric.has(t))
    const isBareNameCandidate =
      !hasSpecificMenuQuery &&
      !looksLikeDiscovery &&
      bareNameWordCount >= 1 &&
      bareNameWordCount <= 8 &&
      bareDistinctiveTokens.length >= 1 &&
      (/^is\s+.+\s+(listed|on qwikker|available|active)\b/i.test(bareNameTrimmed) ||
        /^(details|info|information)\s+(on|about|for)\s+/i.test(bareNameTrimmed) ||
        (!/^(tell me more|tell me about|more about|details about|what about|more on)\b/i.test(
          bareNameTrimmed
        ) &&
          bareNameWordCount <= 6))

    // Explicit detail phrases, practical queries, OR conservative bare-name candidate
    const isDetailQuery =
      (!hasSpecificMenuQuery &&
        /^(tell me more|tell me about|more about|details about|what about|more on)\b/i.test(
          message
        )) ||
      (/\b(hours?|opening|open now|what time|closing|close time|phone|call|contact|address|where is|directions|how do i get|website|book|booking)\b/i.test(
        message
      ) &&
        message.split(/\s+/).length <= 15) ||
      isBareNameCandidate

    // 🎯 CRITICAL FIX: Resolve business from CURRENT message FIRST, scoped to recent candidates
    function resolveBusinessFromCurrentMessage(
      msg: string, 
      recentCandidates: Array<{name: string; slug: string}>
    ): { slug: string | null; matchedBy: string; ambiguous?: boolean } {
      
      if (recentCandidates.length === 0) {
        return { slug: null, matchedBy: 'no_candidates' }
      }
      
      // Normalize for matching
      const normalize = (s: string) => 
        s.toLowerCase()
          .replace(/['']/g, '')
          .replace(/[^\w\s]/g, ' ')
          .replace(/\s+/g, ' ')
          .trim()
      
      const normalized = normalize(msg)
      
      // Extract potential business name tokens (remove common query words)
      const stopWords = [
        'what', 'is', 'are', 'the', 'a', 'an', 'open', 'hours', 'time', 'does', 'do', 
        'when', 'where', 'how', 'can', 'i', 'get', 'to', 'about', 'tell', 'me', 'more', 
        'info', 'information', 'it', 'they', 'close', 'closing', 'opening', 'you', 'your'
      ]
      
      // Banned tokens that are too generic (common in many business names)
      const genericTokens = [
        'restaurant', 'bistro', 'bar', 'grill', 'cafe', 'coffee', 'kitchen', 
        'pub', 'lounge', 'house', 'place', 'spot', 'food'
      ]
      
      const tokens = normalized
        .split(/\s+/)
        .filter(t => t.length >= 3 && !stopWords.includes(t) && !genericTokens.includes(t))
      
      if (tokens.length === 0) {
        return { slug: null, matchedBy: 'no_tokens' }
      }
      
      // Match tokens against recent candidates
      const matches: Array<{biz: {name: string; slug: string}; score: number; matchedTokens: string[]}> = []
      
      for (const biz of recentCandidates) {
        const bizNormalized = normalize(biz.name)
        const bizTokens = bizNormalized.split(/\s+/).filter(t => t.length >= 3)
        
        // Find matching tokens
        const matchingTokens = tokens.filter(t => bizTokens.includes(t))
        
        if (matchingTokens.length >= 2) {
          // Strong match: 2+ tokens
          matches.push({ biz, score: matchingTokens.length * 10, matchedTokens: matchingTokens })
        } else if (matchingTokens.length === 1 && matchingTokens[0].length >= 6) {
          // Medium match: 1 strong token (6+ chars)
          matches.push({ biz, score: 5, matchedTokens: matchingTokens })
        }
      }
      
      if (matches.length === 0) {
        return { slug: null, matchedBy: 'no_match' }
      }
      
      if (matches.length > 1) {
        // Check if there's a clear winner (significantly higher score)
        matches.sort((a, b) => b.score - a.score)
        const topScore = matches[0].score
        const tiedMatches = matches.filter(m => m.score === topScore)
        
        if (tiedMatches.length > 1) {
          // Ambiguous - multiple businesses match equally
          console.log(`⚠️ [AMBIGUOUS MATCH] Multiple businesses match: ${tiedMatches.map(m => m.biz.name).join(', ')}`)
          return { slug: null, matchedBy: 'ambiguous', ambiguous: true }
        }
      }
      
      // Clear winner
      const winner = matches[0]
      console.log(`🎯 [CURRENT MESSAGE MATCH] Found "${winner.biz.name}" via tokens: ${winner.matchedTokens.join(', ')} (score: ${winner.score})`)
      return { slug: winner.biz.slug, matchedBy: 'current_message_token' }
    }

    // Extract recent business candidates from last 2-3 assistant messages
    function extractRecentBusinessCandidates(): Array<{name: string; slug: string}> {
      const recentAssistant = [...(conversationHistory || [])]
        .reverse()
        .filter(m => m?.role === 'assistant')
        .slice(0, 3) // Last 3 assistant messages only
      
      const candidates: Array<{name: string; slug: string}> = []
      const seen = new Set<string>()
      
      for (const m of recentAssistant) {
        const matches = [...(m.content || '').matchAll(/\*\*\[([^\]]+)\]\(\/user\/business\/([a-z0-9-]+)\)\*\*/g)]
        for (const match of matches) {
          const slug = match[2]
          if (!seen.has(slug)) {
            candidates.push({ name: match[1], slug })
            seen.add(slug)
          }
        }
      }
      
      return candidates
    }

    const metaBusinessId = result?.metadata?.currentBusinessId ?? null

    // ✅ Build candidate list from recent conversation
    const recentCandidates = extractRecentBusinessCandidates()
    
    if (process.env.NODE_ENV !== 'production' && recentCandidates.length > 0) {
      console.log(`📋 [RECENT CANDIDATES] ${recentCandidates.length} businesses: ${recentCandidates.map(c => c.name).join(', ')}`)
    }

    // ✅ PRIORITY 1: Try to resolve from CURRENT message (scoped to recent candidates)
    // ✅ PRIORITY 2: Fall back to history only if current message has no business mention
    let resolvedSlug: string | null = null
    let resolvedBusinessId: string | null = null
    let matchedBy = 'none'
    
    if (isDetailQuery) {
      // Try current message first (scoped to recent candidates)
      const currentMatch = resolveBusinessFromCurrentMessage(message, recentCandidates)
      
      if (currentMatch.ambiguous) {
        // Multiple businesses match - don't guess, let AI ask for clarification
        console.log(`⚠️ [RESOLVER] Ambiguous match - will not auto-select business`)
        matchedBy = 'ambiguous'
      } else if (currentMatch.slug) {
        resolvedSlug = currentMatch.slug
        matchedBy = currentMatch.matchedBy
      } else {
        // Fall back to history only if no match in current message
        resolvedSlug = inferSelectedBusinessSlugFromHistory(message, conversationHistory || [])
        matchedBy = resolvedSlug ? 'history_fallback' : 'none'
      }

      // 🔍 FALLBACK: If no match from candidates or history, try direct DB lookup by name
      // This handles fresh conversations where user asks about a specific business.
      // MUST search all three chat tiers — chat_eligible alone excludes unclaimed T3.
      if (!resolvedSlug && matchedBy !== 'ambiguous') {
        console.log(`🔍 [DB LOOKUP] Attempting direct name search for: "${message}" (city: ${city})`)
        try {
          const { createServiceRoleClient: createSR } = await import('@/lib/supabase/server')
          const supabase = createSR()
          const stopWords = new Set([
            'what', 'is', 'are', 'the', 'a', 'an', 'open', 'hours', 'time', 'does', 'do',
            'when', 'where', 'how', 'can', 'i', 'get', 'to', 'about', 'tell', 'me', 'more',
            'info', 'information', 'close', 'closing', 'opening', 'for', 'of', 'at', 'in', 'on',
          ])
          const genericTokens = new Set([
            'restaurant', 'restaurants', 'bar', 'bars', 'cafe', 'cafes', 'grill', 'bistro',
            'pub', 'lounge', 'house', 'club', 'and',
          ])
          const nameTokens = message
            .toLowerCase()
            .replace(/&/g, ' and ')
            .replace(/[^\w\s]/g, ' ')
            .split(/\s+/)
            .filter((t) => t.length >= 2 && !stopWords.has(t))
          const distinctiveTokens = nameTokens.filter((t) => !genericTokens.has(t) && t.length >= 3)

          console.log(`🔍 [DB LOOKUP] Name tokens: [${nameTokens.join(', ')}]`)
          console.log(`🔍 [DB LOOKUP] Distinctive tokens: [${distinctiveTokens.join(', ')}]`)

          const lookupViews = [
            'business_profiles_chat_eligible',
            'business_profiles_lite_eligible',
            'business_profiles_ai_fallback_pool',
          ] as const

          const scoreCandidate = (businessName: string): number => {
            const norm = businessName
              .toLowerCase()
              .replace(/&/g, ' and ')
              .replace(/[^\w\s]/g, ' ')
              .replace(/\s+/g, ' ')
              .trim()
            const bizTokens = norm.split(' ').filter((t) => t.length >= 2)
            const tokensForScore = distinctiveTokens.length > 0 ? distinctiveTokens : nameTokens
            // Prefer exact token hits: "che" in "CHE Rock Bar" beats prefix into "Cheetah"
            const exactMatched = tokensForScore.filter((t) => bizTokens.some((bt) => bt === t))
            const fuzzyMatched = tokensForScore.filter(
              (t) =>
                !exactMatched.includes(t) &&
                bizTokens.some(
                  (bt) =>
                    (t.length >= 4 && (bt.includes(t) || t.includes(bt))) ||
                    (bt.startsWith(t) && bt.length >= t.length + 3)
                )
            )
            if (exactMatched.length === tokensForScore.length && tokensForScore.length >= 2) {
              return 90 + exactMatched.length * 5
            }
            if (exactMatched.length >= 2) return 70 + exactMatched.length * 5
            if (exactMatched.length === 1 && exactMatched[0].length >= 6) return 55
            if (exactMatched.length === 1 && tokensForScore.length === 1) return 48
            if (exactMatched.length + fuzzyMatched.length >= 2) return 40 + exactMatched.length * 8
            return 0
          }

          const mergeMatches = (rows: { id: string; business_name: string }[]) => {
            for (const row of rows) {
              if (!dbById.has(row.id)) dbById.set(row.id, row)
            }
          }

          const dbById = new Map<string, { id: string; business_name: string }>()
          let dbMatches: { id: string; business_name: string }[] = []

          if (distinctiveTokens.length >= 2 || nameTokens.length >= 2) {
            // AND-match across ALL tiers (merge — do not stop at first view)
            const andTokens =
              distinctiveTokens.length >= 2 ? distinctiveTokens.slice(0, 4) : nameTokens.slice(0, 4)
            for (const view of lookupViews) {
              let q = supabase.from(view).select('id, business_name').eq('city', city)
              for (const token of andTokens) {
                q = q.ilike('business_name', `%${token}%`)
              }
              const { data, error } = await q.limit(12)
              if (error) {
                console.log(`🔍 [DB LOOKUP] ${view} error: ${error.message}`)
                continue
              }
              if (data?.length) {
                mergeMatches(data)
                console.log(
                  `🔍 [DB LOOKUP] ${view} AND-match (${andTokens.join('+')}): ${data.map((b) => b.business_name).join(', ')}`
                )
              }
            }

            // Named-ask safety net: claimed/approved profiles can be missing from chat
            // views (e.g. empty menu_preview). Search live profiles directly.
            if (dbById.size === 0) {
              let q = supabase
                .from('business_profiles')
                .select('id, business_name')
                .eq('city', city)
                .in('status', ['claimed_free', 'approved', 'active'])
              for (const token of andTokens) {
                q = q.ilike('business_name', `%${token}%`)
              }
              const { data, error } = await q.limit(12)
              if (!error && data?.length) {
                mergeMatches(data)
                console.log(
                  `🔍 [DB LOOKUP] business_profiles AND-match fallback: ${data.map((b) => b.business_name).join(', ')}`
                )
              }
            }
          }

          // Phrase / single-token fallbacks if AND-match missed
          if (dbById.size === 0 && distinctiveTokens.length > 0) {
            const searchTerm = distinctiveTokens.join(' ')
            console.log(`🔍 [DB LOOKUP] Searching for: "${searchTerm}"`)
            for (const view of lookupViews) {
              const { data, error } = await supabase
                .from(view)
                .select('id, business_name')
                .eq('city', city)
                .ilike('business_name', `%${searchTerm}%`)
                .limit(12)
              if (!error && data?.length) mergeMatches(data)
            }
            if (dbById.size === 0) {
              const { data } = await supabase
                .from('business_profiles')
                .select('id, business_name')
                .eq('city', city)
                .in('status', ['claimed_free', 'approved', 'active'])
                .ilike('business_name', `%${searchTerm}%`)
                .limit(12)
              if (data?.length) mergeMatches(data)
            }
          }

          dbMatches = Array.from(dbById.values())

          // Prefer a business already in this turn's candidate list / history
          if (dbMatches.length > 1 && recentCandidates.length > 0) {
            const candidateSlugs = new Set(recentCandidates.map((c) => c.slug))
            const inConversation = dbMatches.filter((b) =>
              candidateSlugs.has(generateSlugFromName(b.business_name))
            )
            if (inConversation.length === 1) {
              console.log(
                `🔍 [DB LOOKUP] Preferring conversation candidate: ${inConversation[0].business_name}`
              )
              dbMatches = inConversation
            }
          }

          // Score multi-candidates — prefer CHE Rock Bar over Cheetah's Rock for "che rock …"
          if (dbMatches.length > 1) {
            const ranked = dbMatches
              .map((b) => ({ b, score: scoreCandidate(b.business_name) }))
              .filter((x) => x.score >= 40)
              .sort((a, b) => b.score - a.score)
            if (ranked.length === 1 || (ranked.length > 1 && ranked[0].score >= ranked[1].score + 5)) {
              dbMatches = [ranked[0].b]
              console.log(
                `🔍 [DB LOOKUP] Scored best match: "${ranked[0].b.business_name}" (score ${ranked[0].score})`
              )
            } else if (ranked.length > 0) {
              console.log(
                `⚠️ [DB LOOKUP] Ambiguous (close scores): ${ranked.map((r) => `${r.b.business_name}:${r.score}`).join(', ')}`
              )
              dbMatches = []
            } else {
              console.log(`⚠️ [DB LOOKUP] Ambiguous: ${dbMatches.map((b) => b.business_name).join(', ')}`)
              dbMatches = []
            }
          }

          console.log(
            `🔍 [DB LOOKUP] Results: ${dbMatches.length} matches${
              dbMatches.length ? ` — ${dbMatches.map((b) => b.business_name).join(', ')}` : ''
            }`
          )

          if (dbMatches.length === 1) {
            resolvedBusinessId = dbMatches[0].id
            resolvedSlug = generateSlugFromName(dbMatches[0].business_name)
            matchedBy = 'db_name_lookup'
            console.log(
              `🔍 [DB LOOKUP] Found "${dbMatches[0].business_name}" via name search across chat tiers`
            )
          }
        } catch (err) {
          console.error('[DB LOOKUP] Error:', err)
        }
      }
    }

    if (process.env.NODE_ENV !== 'production') {
      console.log('📋 [DETAIL MODE CHECK]', {
        isDetailQuery,
        currentMessage: message,
        messageLength: message.split(/\s+/).length,
        resolvedSlug,
        resolvedBusinessId,
        matchedBy,
        candidateCount: recentCandidates.length
      })
    }

    const currentBusinessId = metaBusinessId || resolvedBusinessId
    const currentBusinessSlug = resolvedSlug || result?.metadata?.currentBusinessSlug || null

    const isDetailMode = !!(isDetailQuery && (currentBusinessId || currentBusinessSlug))

    if (process.env.NODE_ENV !== 'production') {
      console.log('📋 [DETAIL MODE RESULT]', {
        isDetailMode,
        metaBusinessId,
        currentBusinessSlug,
        matchedBy,
        willFetch: isDetailMode && (currentBusinessId || currentBusinessSlug)
      })
    }
    
    if (isDetailMode && (currentBusinessId || currentBusinessSlug)) {
      console.log(`📋 [DETAIL MODE] Fetching full business details`)
      
      try {
        // Service role — same as DB name lookup. Anon/tenant client + RLS cannot
        // read T3 unclaimed rows in business_profiles_ai_fallback_pool, which caused
        // "Found Cheetah's Rock" then "No business found for ID=…" drops.
        const supabase = createServiceRoleClient()
        
        // Fetch business with specific fields (matching actual DB columns)
        const selectFields = `
          id,
          business_name,
          display_category,
          rating,
          review_count,
          business_address,
          business_town,
          business_postcode,
          phone,
          website_url,
          business_description,
          business_hours,
          business_hours_structured,
          latitude,
          longitude
        `
        
        let biz = null
        let matchedBy = 'none'

        // 1️⃣ Try ID across all chat tiers (T1 paid + T2 lite + T3 unclaimed)
        const detailViews = [
          'business_profiles_chat_eligible',
          'business_profiles_lite_eligible',
          'business_profiles_ai_fallback_pool',
        ] as const

        if (currentBusinessId) {
          for (const view of detailViews) {
            const { data } = await supabase
              .from(view)
              .select(selectFields)
              .eq('id', currentBusinessId)
              .eq('city', city)
              .maybeSingle()

            if (data) {
              biz = data
              matchedBy = `id:${view}`
              break
            }
          }
        }

        // 2️⃣ Fallback: resolve from inferredSlug -> business_name ilike, scoped to city
        if (!biz && currentBusinessSlug) {
          const words = currentBusinessSlug.split('-').filter((w) => w.length > 1)
          const pattern = `%${words.join('%')}%` // e.g. "%cheetah%rock%" (drop lone "s" from Cheetah's)

          for (const view of detailViews) {
            const { data } = await supabase
              .from(view)
              .select(selectFields)
              .eq('city', city)
              .ilike('business_name', pattern)
              .order('review_count', { ascending: false })
              .limit(1)
              .maybeSingle()

            if (data) {
              biz = data
              matchedBy = `name_from_slug:${view}`
              break
            }
          }
        }

        if (process.env.NODE_ENV !== 'production') {
          console.log('📋 [DETAIL MODE] selected', {
            currentBusinessId,
            currentBusinessSlug,
            found: !!biz,
            matchedBy
          })
        }
        
        if (biz) {
          console.log(`✅ [DETAIL MODE] Found business: ${biz.business_name}`)
          
          // Address deduplication helpers
          function normalizeAddress(str: string) {
            return str
              .replace(/\s+/g, ' ')
              .replace(/\s*,\s*/g, ', ')
              .replace(/,+/g, ',')
              .replace(/,\s*$/g, '')
              .trim()
          }
          
          function dedupeAddressParts(full: string, parts: string[]) {
            let out = full
            for (const part of parts.filter(Boolean)) {
              const p = part.trim()
              if (!p) continue
              // if full already includes part (case-insensitive), skip
              const re = new RegExp(p.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i')
              if (re.test(out)) continue
              out = normalizeAddress(`${out}, ${p}`)
            }
            return normalizeAddress(out)
          }
          
          function formatBusinessAddress(b: any) {
            const base = normalizeAddress(b.business_address || '')
            const town = normalizeAddress(b.business_town || '')
            const postcode = normalizeAddress(b.business_postcode || '')
            
            if (!base) {
              // build from parts if base is missing
              return normalizeAddress([town, postcode].filter(Boolean).join(', '))
            }
            
            // If base already includes postcode/town, don't append them
            return dedupeAddressParts(base, [town, postcode])
          }
          
          // Detect specific info requests (hours only, phone only, etc.)
          const asksHoursOnly = /\b(hours?|opening|open|close|closing|what time)\b/i.test(message) && 
                                !/\b(tell me|more about|details|info|everything|all about)\b/i.test(message)
          const asksPhoneOnly = /\b(phone|number|call|contact number)\b/i.test(message) && 
                                !/\b(tell me|more about|details|everything)\b/i.test(message)
          const asksAddressOnly = /\b(address|where is|location|directions)\b/i.test(message) && 
                                  !/\b(tell me|more about|details|everything)\b/i.test(message)
          
          // Build deterministic facts block (NO EMOJIS, clean labels)
          const facts: string[] = []
          const slug = generateSlugFromName(biz.business_name)
          
          // If asking for specific info only, don't repeat entire profile
          const isSpecificQuery = asksHoursOnly || asksPhoneOnly || asksAddressOnly
          
          if (!isSpecificQuery) {
            // Full profile header
            facts.push(`**[${biz.business_name}](/user/business/${slug})**`)
            facts.push('') // blank line
            
            // Business description (owner's voice) — trim & cap at 800 chars
            const desc = biz.business_description?.trim()
            if (desc && desc.length > 0) {
              facts.push(desc.slice(0, 800))
              facts.push('') // blank line after description
            }
            
            // Rating (only if has reviews) - NO EMOJI
            if (biz.rating && biz.review_count > 0) {
              facts.push(`**Rating:** ${biz.rating}★ (${biz.review_count} reviews)`)
            }
            
            // Category - NO EMOJI
            if (biz.display_category) {
              facts.push(`**Category:** ${biz.display_category}`)
            }

            // Qwikker Vibes
            try {
              const { getBusinessVibeStats } = await import('@/lib/utils/vibes')
              const vibeStats = await getBusinessVibeStats(biz.id)
              if (vibeStats && vibeStats.total_vibes >= 5) {
                facts.push(`**💚 Qwikker Vibes 💚** ${vibeStats.positive_percentage}% positive (${vibeStats.total_vibes} vibes)`)
              }
            } catch {}
          } else {
            // Business name with link for specific queries
            facts.push(`**[${biz.business_name}](/user/business/${slug})**`)
            facts.push('') // blank line
          }
          
          // Opening hours - NO EMOJI (always show if available, or if specifically asked)
          const wantsFullHours = /\b(full hours|all hours|weekly hours|hours for the week|hours during the week|week hours|hours this week|opening hours for the week|weekly schedule|complete hours|entire schedule|what time|what are the hours|when.*open|opening hours)\b/i.test(message)
          
          if ((asksHoursOnly || wantsFullHours) && biz.business_hours_structured) {
            if (wantsFullHours) {
              function formatWeeklyHours(rawData: any): string {
                const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
                const dayLabels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
                
                const lines: string[] = []
                for (let i = 0; i < days.length; i++) {
                  const dayData = rawData[days[i]]
                  if (!dayData) continue
                  
                  if (dayData.closed === true) {
                    lines.push(`${dayLabels[i]}: Closed`)
                  } else if (dayData.open && dayData.close) {
                    const parseTime = (t: string) => {
                      const [h, m] = t.split(':').map(Number)
                      const ampm = h >= 12 ? 'pm' : 'am'
                      const hour12 = h % 12 === 0 ? 12 : h % 12
                      return m === 0 ? `${hour12}${ampm}` : `${hour12}:${String(m).padStart(2, '0')}${ampm}`
                    }
                    lines.push(`${dayLabels[i]}: ${parseTime(dayData.open)} – ${parseTime(dayData.close)}`)
                  }
                }
                
                return lines.length > 0 ? lines.join('\n') : 'Hours not available'
              }
              
              const weeklySchedule = formatWeeklyHours(biz.business_hours_structured)
              const weeklyBullets = weeklySchedule.split('\n').map(l => `- ${l}`).join('\n')
              facts.push(`**Hours:**\n${weeklyBullets}`)
              console.log('🕒 [FULL HOURS] Showing weekly schedule (structured)')
            } else {
              const openStatus = getOpenStatusForToday(biz.business_hours_structured, new Date())
              console.log('🕒 [DETAIL MODE HOURS]', { 
                hasHours: openStatus.hasHours, 
                todaySummary: openStatus.todaySummary, 
                conversational: openStatus.conversational,
                rawData: biz.business_hours_structured
              })
              if (openStatus.hasHours && openStatus.conversational && openStatus.todaySummary) {
                facts.push(`**Hours:** ${openStatus.conversational} (${openStatus.todaySummary})`)
              }
            }
          } else if ((asksHoursOnly || wantsFullHours) && biz.business_hours) {
            facts.push(`**Hours:**\n${biz.business_hours}`)
            console.log('🕒 [FULL HOURS] Showing text hours (no structured data)')
          } else if (asksHoursOnly || wantsFullHours) {
            facts.push(`**Hours:** I don't have the full hours for ${biz.business_name} yet.`)
            if (biz.phone) facts.push(`Try calling ${biz.phone} or check their website.`)
          }
          
          // Only show other details if NOT a hours-only query
          if (!asksHoursOnly || !isSpecificQuery) {
            // Address - NO EMOJI, deduplicated (show if not hours-only OR if address-only)
            if (asksAddressOnly || !isSpecificQuery) {
              const address = formatBusinessAddress(biz)
              if (address) {
                facts.push(`**Address:** ${address}`)
              }
            }
            
            // Phone - NO EMOJI (show if phone-only OR full details)
            if ((asksPhoneOnly || !isSpecificQuery) && biz.phone) {
              facts.push(`**Phone:** ${biz.phone}`)
            }
            
            // Website - NO EMOJI (only in full details)
            if (!isSpecificQuery && biz.website_url) {
              facts.push(`**Website:** ${biz.website_url}`)
            }
            
            // Directions link (only if user asks AND coordinates exist) - NO EMOJI
            const asksDirections = /\b(directions?|how do i get|where is|map)\b/i.test(message)
            if (asksDirections && biz.latitude && biz.longitude) {
              const lat = biz.latitude
              const lng = biz.longitude
              facts.push(`**Directions:** [Get Directions](https://www.google.com/maps/search/?api=1&query=${lat},${lng})`)
            }
          }
          
          const detailFactsBlock = facts.join('\n')
          
          // 🚨 DETAIL MODE: SHORT-CIRCUIT - Return immediately, bypass browse/carousel/pins
          console.log(`✅ [DETAIL MODE] Built facts block (${detailFactsBlock.length} chars) - RETURNING EARLY`)
          
          // Only show Atlas CTA if THIS business has coords
          const hasCoords = !!(biz.latitude && biz.longitude)
          
          // Persist detail-mode messages
          await persistChatMessages(sessionId, validatedWalletPassId, message, detailFactsBlock, undefined, city)

          return NextResponse.json({
            response: detailFactsBlock,
            intent: 'unknown',
            needsLocation: false,
            showAtlasCta: false,
            businessCarousel: [],
            eventCards: [],
            mapPins: hasCoords ? [{
              id: biz.id,
              name: biz.business_name,
              latitude: biz.latitude,
              longitude: biz.longitude,
              category: biz.display_category || 'Business',
              tier: 'detail'
            }] : [],
            sources: [],
            quickReplies: [],
            metadata: {
              mode: 'detail',
              matchedBy: currentBusinessSlug ? 'slug' : 'id',
              currentBusinessSlug,
              currentBusinessId: biz.id
            }
          })
        } else {
          // FAIL CLOSED: No business found, don't hallucinate
          console.log(`⚠️ [DETAIL MODE] No business found for ID=${currentBusinessId} or slug=${currentBusinessSlug}`)
          // Continue to normal flow (will use AI response)
        }
      } catch (error) {
        console.error('[DETAIL MODE] Error fetching business details:', error)
        // Continue to normal flow on error
      }
    }
    
    if (!showAtlasCta && finalResponse) {
      // Strip ANY sentence containing "Atlas" or map references (robust catch-all)
      const beforeStrip = finalResponse
      finalResponse = finalResponse
        .replace(/[^.!?\n]*\b[Aa]tlas\b[^.!?\n]*[.!?]?\s*/g, '')
        .replace(/[^.!?\n]*\bmap below\b[^.!?\n]*[.!?]?\s*/g, '')
        .replace(/[^.!?\n]*\bmap view\b[^.!?\n]*[.!?]?\s*/g, '')
        .replace(/  +/g, ' ')
        .replace(/\n{3,}/g, '\n\n')
        .trim()
      
      if (process.env.NODE_ENV === 'development' && finalResponse !== beforeStrip) {
        console.log('🔧 Stripped Atlas/map mentions from response (showAtlasCta=false)')
      }
    }
    
    // 🔧 DETAIL MODE: Strip generic footer from model response
    if (isDetailMode && finalResponse) {
      const footerPatterns = [
        /If you'?d like more details about.*?I'?ll pull up.*?\./gi,
        /tell me which (?:place|one).*?I'?ll pull up.*?\./gi,
        /Let me know which.*?I can share.*?\./gi,
        /Want to know more about.*?Just ask.*?\./gi
      ]
      
      footerPatterns.forEach(pattern => {
        finalResponse = finalResponse.replace(pattern, '')
      })
      
      // Clean up trailing whitespace
      finalResponse = finalResponse.replace(/\n{3,}/g, '\n\n').trim()
    }
    
    // 🔗 AUTO-LINK: Inject links for bold business names the AI forgot to link
    // contextBusinesses = every business sent to the AI prompt (guaranteed superset of carousel/mapPins)
    const allKnownBusinesses = [
      ...(result.businessCarousel || []),
      ...(result.mapPins || []).map((p: any) => ({ business_name: p.business_name || p.name, slug: p.slug, id: p.id })),
      ...(result.contextBusinesses || []),
    ]
    finalResponse = autoInjectBusinessLinks(finalResponse, allKnownBusinesses)

    // 🗺️ Scope Atlas pins to businesses the reply actually linked.
    // Stops "1 place suggested → Take a tour (12 places)".
    let atlasPins = nameMatchSuppressed ? [] : [...(result.mapPins || [])]
    const linkedSlugs = new Set(
      [...finalResponse.matchAll(/\/user\/business\/([a-z0-9-]+)/gi)].map((m) => m[1].toLowerCase())
    )
    if (linkedSlugs.size > 0 && atlasPins.length > 0) {
      const slugify = (name: string) =>
        name.toLowerCase().replace(/['']/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      const scoped = atlasPins.filter((p: any) => {
        const slug = String(p.slug || slugify(p.business_name || p.name || '')).toLowerCase()
        return linkedSlugs.has(slug)
      })
      if (scoped.length > 0) {
        console.log(`🗺️ ATLAS pins scoped to ${scoped.length} linked business(es) (was ${atlasPins.length})`)
        atlasPins = scoped
      }
    }

    const scopedAtlasCount = atlasPins.filter(hasValidAtlasCoord).length
    // Recompute CTA from scoped pins (1 place is enough — user still wants Atlas)
    if (!responseSaysNoResults && !nameMatchSuppressed && !isEventOnlyQuery && scopedAtlasCount >= 1) {
      showAtlasCta = true
    } else if (scopedAtlasCount === 0 || responseSaysNoResults) {
      showAtlasCta = false
    }

    // Atlas footer copy — singular/plural must match scoped pin count
    if (finalResponse) {
      finalResponse = finalResponse
        .replace(/[^.!?\n]*\b[Aa]tlas\b[^.!?\n]*[.!?]?\s*/g, '')
        .replace(/[^.!?\n]*\bmap below\b[^.!?\n]*[.!?]?\s*/g, '')
        .replace(/  +/g, ' ')
        .replace(/\n{3,}/g, '\n\n')
        .trim()
    }
    if (showAtlasCta && finalResponse) {
      const atlasLine = scopedAtlasCount === 1
        ? 'Tap **Explore on Atlas** below to see this spot on the map!'
        : 'Tap **Explore on Atlas** below to take a guided tour of these spots on the map!'
      finalResponse = finalResponse.trimEnd() + `\n\n${atlasLine}`
    }

    // 🚨 HALLUCINATION GUARD: Strip bold from non-linked names (likely hallucinated businesses)
    // Runs AFTER autoInjectBusinessLinks so all known Qwikker businesses are already **[Name](link)** format
    // The [^[*] pattern excludes '[', so linked names won't match -- only plain **Bold Text** remains
    finalResponse = finalResponse.replace(/\*\*([^[*]+?)\*\*/g, (match, inner) => {
      const trimmed = inner.trim()
      if (/Explore on Atlas|Qwikker Pick/i.test(trimmed)) return match
      if (/^[A-Z]/.test(trimmed) && trimmed.length >= 3) {
        if (process.env.NODE_ENV === 'development') {
          console.warn(`⚠️ [HALLUCINATION GUARD] Stripped bold from non-linked name: "${trimmed}"`)
        }
        return trimmed
      }
      return match
    })

    // 🎯 FINAL FORMATTING: Force business paragraphs (MUST BE LAST STEP)
    // This runs AFTER all text mutations (Atlas stripping, etc.)
    finalResponse = forceNewParagraphPerBusinessLink(finalResponse)
    
    // 🚨 GUARDRAIL: Catch vague responses when data exists (dev-only warning)
    if (process.env.NODE_ENV === 'development') {
      const bannedVagueness = [
        'typically open',
        'usually open',
        'check their site',
        'confirm on their site',
        'might be open',
        'probably open',
        'tends to be open',
        'generally open'
      ]
      
      for (const phrase of bannedVagueness) {
        if (finalResponse.toLowerCase().includes(phrase)) {
          console.error(`🚨 [VAGUENESS DETECTED] Response contains "${phrase}" - model is hedging when data likely exists!`)
        }
      }
    }
    
    // 📞 CONTEXT-AWARE FOOTER
    const businessLinkMatches = finalResponse.match(/\*\*\[[^\]]+\]\(\/user\/business\/[a-z0-9-]+\)\*\*/g) || []
    const businessLinkCount = businessLinkMatches.length
    
    // Use final (fallback-aware) selection state
    const userHasSelectedBusiness = !!(currentBusinessId || currentBusinessSlug)
    
    // Show footer ONLY when:
    // - We have 2+ businesses listed (choice mode)
    // - User hasn't selected a business yet
    // - NOT in detail mode
    if (businessLinkCount >= 2 && !userHasSelectedBusiness && !isDetailMode) {
      finalResponse += `\n\nIf you'd like more details about one of these, tell me which place and I'll pull up directions, opening hours, and contact details.`
    }
    
    // 🔍 DEV-ONLY: Verify paragraph spacing is preserved
    if (process.env.NODE_ENV === 'development') {
      const hasDoubleNewlines = finalResponse.includes('\n\n')
      console.log(`✅ [FINAL] Paragraph spacing preserved: ${hasDoubleNewlines}, ${businessLinkCount} business links`)
      
      // Warn if 2+ businesses but no paragraph breaks (should never happen now)
      if (businessLinkCount >= 2 && !hasDoubleNewlines) {
        console.warn(`⚠️  [FINAL] ${businessLinkCount} business links but NO paragraph breaks - formatter may have failed!`)
      }
    }
    
    // Prefer server-authored chips from hybrid (e.g. offer pitch). Never invent from the model.
    const quickReplies: string[] = Array.isArray(result.quickReplies)
      ? result.quickReplies.slice(0, 4)
      : []
    
    if (process.env.NODE_ENV === 'development') {
      console.log('✨ Quick replies (server-authored):', quickReplies)
    }

    // Categorize the message for analytics
    const messageCategory = await categorizeUserMessage(message)
    console.log(`📊 Message category: ${messageCategory.category} (confidence: ${messageCategory.confidence})`)

    console.log('🎯 API RESPONSE:', {
      intent,
      needsLocation,
      showAtlasCta,
      hasBusinessResults: result.hasBusinessResults,
      businessCarouselCount: result.businessCarousel?.length || 0,
      eventCardsCount: result.eventCards?.length || 0
    })

    // Persist messages (awaited to prevent Next.js context teardown, ~50ms)
    await persistChatMessages(sessionId, validatedWalletPassId, message, finalResponse, {
      quickReplies,
      intent,
    }, city)

    return NextResponse.json({
      response: finalResponse,
      intent,
      needsLocation,
      showAtlasCta,
      sources: result.sources || [],
      quickReplies,
      hasBusinessResults: result.hasBusinessResults,
      businessCarousel: result.businessCarousel,
      mapPins: atlasPins, // Scoped to businesses actually linked in the reply
      queryCategories: result.queryCategories || [], // ✅ ATLAS: For filtering businesses by query
      queryKeywords: result.queryKeywords || [], // ✅ ATLAS: For filtering businesses by query
      walletActions: result.walletActions,
      eventCards: result.eventCards,
      googleReviewSnippets: result.googleReviewSnippets,
      metadata: {
        city,
        userName,
        category: messageCategory.category,
        sourceCount: result.sources?.length || 0,
        modelUsed: result.modelUsed,
        complexity: result.classification?.complexity,
        intent
      }
    })

  } catch (error) {
    console.error('❌ AI Chat API error:', error)
    
    // Get city for personalized fallback message
    const fallbackCity = await getFranchiseCityFromRequest() || 'this city'
    const cityDisplayName = fallbackCity.charAt(0).toUpperCase() + fallbackCity.slice(1)
    
    return NextResponse.json({
      response: `I'm still getting to know ${cityDisplayName}. As local businesses verify details, I'll be able to recommend specific dishes, offers and hidden spots. For now, explore what's already live in the Discover section and your pass will update automatically.`,
      intent: 'unknown',
      needsLocation: false,
      showAtlasCta: false,
      sources: [],
      quickReplies: [], // REMOVED: Let users type what they want
      error: 'Internal server error'
    }, { status: 500 })
  }
}

// Handle preflight requests for CORS
export async function OPTIONS() {
  return new NextResponse(null, {
    status: 200,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    },
  })
}
