-- =====================================================
-- QWIKKER LOYALTY SYSTEM V1 MIGRATION
-- Date: 2026-02-09
-- Purpose: Create 5 loyalty tables, add date_of_birth
-- to app_users, enable RLS with EXISTS-based policies.
-- =====================================================

-- =====================================================
-- PRE-FLIGHT: verify business_profiles exists
-- =====================================================
do $$
begin
  if not exists (
    select 1 from information_schema.tables
    where table_schema = 'public'
      and table_name = 'business_profiles'
  ) then
    raise exception 'business_profiles table does not exist. Cannot create loyalty system.';
  end if;
end $$;

-- =====================================================
-- 1. ADD date_of_birth TO app_users
-- =====================================================
alter table public.app_users
  add column if not exists date_of_birth date;

comment on column public.app_users.date_of_birth
  is 'Optional date of birth collected during loyalty join flow. Used for future birthday rewards.';

-- =====================================================
-- 2. loyalty_programs
-- One program per business. City is the tenancy boundary.
-- =====================================================
create table public.loyalty_programs (
  id                          uuid primary key default gen_random_uuid(),
  business_id                 uuid not null references public.business_profiles(id) on delete cascade,
  public_id                   text not null,
  program_name                text,
  type                        text not null default 'stamps'
                              check (type in ('stamps', 'points')),
  reward_threshold            int not null,
  reward_description          text not null,
  stamp_label                 text default 'Stamps',
  earn_mode                   text not null default 'per_visit'
                              check (earn_mode in ('per_visit', 'per_transaction')),
  stamp_icon                  text not null default 'stamp',
  earn_instructions           text,
  redeem_instructions         text,
  primary_color               varchar(7),
  background_color            varchar(7),
  logo_url                    text,
  logo_description            text,
  strip_image_url             text,
  strip_image_description     text,
  terms_and_conditions        text,
  status                      text not null default 'draft'
                              check (status in ('draft', 'submitted', 'active', 'paused')),
  walletpush_template_id      text,
  walletpush_api_key          text,
  walletpush_pass_type_id     text,
  counter_qr_token            text not null default encode(gen_random_bytes(16), 'hex'),
  previous_counter_qr_token   text,
  counter_qr_token_rotated_at timestamptz default now(),
  timezone                    text not null default 'Europe/London',
  max_earns_per_day           int not null default 1
                              check (max_earns_per_day >= 1 and max_earns_per_day <= 5),
  min_gap_minutes             int not null default 30
                              check (min_gap_minutes >= 0 and min_gap_minutes <= 180),
  birthday_bonus_enabled      boolean default false,
  birthday_bonus_reward       text,
  birthday_bonus_valid_days   int default 7,
  premium_flags               jsonb default '{
    "push_to_loyalty": true,
    "member_export": true,
    "birthday_rewards": false,
    "bonus_multipliers": false,
    "advanced_earn_rules": false
  }'::jsonb,
  city                        text not null,
  created_at                  timestamptz default now(),
  updated_at                  timestamptz default now()
);

comment on table public.loyalty_programs
  is 'Loyalty programs -- one per business (Spotlight tier). Stores program config, earn rules, branding, and WalletPush credentials.';

comment on column public.loyalty_programs.public_id
  is 'Short random ID (Base62, 10 chars) for public-facing URLs. Generated by app via generateShortCode().';

comment on column public.loyalty_programs.stamp_icon
  is 'Visual icon key for rewards grid: stamp, bean, scissors, chilli, burger, cocktail, pizza, star, heart, cake, dumbbell, paw.';

comment on column public.loyalty_programs.walletpush_api_key
  is 'API key scoped to this business loyalty template in WalletPush. Stored in plaintext (V1). Set by city admin on activation.';

comment on column public.loyalty_programs.counter_qr_token
  is 'Secret token embedded in earn QR code at the till. Proves physical presence. Rotatable by business owner.';

comment on column public.loyalty_programs.premium_flags
  is 'Feature flags for future monetisation gating. All true for Spotlight in V1.';

-- Unique constraint: one program per business
alter table public.loyalty_programs
  add constraint loyalty_programs_business_id_unique unique (business_id);

-- Unique constraint: public_id globally unique
alter table public.loyalty_programs
  add constraint loyalty_programs_public_id_unique unique (public_id);

-- Indexes
create index idx_loyalty_programs_city_status
  on public.loyalty_programs(city, status);

-- =====================================================
-- 3. loyalty_pass_requests
-- Frozen snapshot of submitted specs for admin review.
-- =====================================================
create table public.loyalty_pass_requests (
  id                          uuid primary key default gen_random_uuid(),
  business_id                 uuid not null references public.business_profiles(id) on delete cascade,
  design_spec_json            jsonb not null,
  status                      text not null default 'submitted'
                              check (status in ('submitted', 'issued', 'rejected')),
  rejection_reason            text,
  walletpush_template_id      text,
  walletpush_api_key          text,
  walletpush_pass_type_id     text,
  reviewed_by_admin_id        uuid,
  created_at                  timestamptz default now()
);

comment on table public.loyalty_pass_requests
  is 'Frozen snapshots of loyalty card specs submitted by businesses. Used by city admin to create WalletPush templates.';

-- Index for admin queue queries
create index idx_loyalty_pass_requests_status
  on public.loyalty_pass_requests(status)
  where status = 'submitted';

create index idx_loyalty_pass_requests_business
  on public.loyalty_pass_requests(business_id);

-- =====================================================
-- 4. loyalty_memberships
-- User membership in a loyalty program. Service-role
-- writes only (no direct user INSERT/UPDATE via RLS).
-- =====================================================
create table public.loyalty_memberships (
  id                          uuid primary key default gen_random_uuid(),
  program_id                  uuid not null references public.loyalty_programs(id) on delete cascade,
  user_wallet_pass_id         text not null,
  stamps_balance              int not null default 0,
  points_balance              int not null default 0,
  total_earned                int not null default 0,
  total_redeemed              int not null default 0,
  last_earned_at              timestamptz,
  earned_today_count          int not null default 0,
  earned_today_date           date,
  joined_at                   timestamptz default now(),
  walletpush_serial           text,
  status                      text not null default 'active'
                              check (status in ('active', 'inactive')),
  last_active_at              timestamptz default now(),
  birthday_bonus_redeemed_year int,
  created_at                  timestamptz default now()
);

comment on table public.loyalty_memberships
  is 'User memberships in loyalty programs. All writes via service role (API endpoints). Users can only SELECT their own.';

comment on column public.loyalty_memberships.user_wallet_pass_id
  is 'Links to app_users.wallet_pass_id. Not a FK because wallet_pass_id is assigned externally by WalletPush.';

comment on column public.loyalty_memberships.walletpush_serial
  is 'Serial number of the issued WalletPush loyalty pass. NULL until pass is issued (credentials may not exist yet).';

comment on column public.loyalty_memberships.earned_today_count
  is 'Tracks stamps earned today (in program timezone). Reset when earned_today_date changes.';

-- One membership per user per program
alter table public.loyalty_memberships
  add constraint loyalty_memberships_program_user_unique
  unique (program_id, user_wallet_pass_id);

-- Indexes
create index idx_loyalty_memberships_user
  on public.loyalty_memberships(user_wallet_pass_id);

create index idx_loyalty_memberships_program_status
  on public.loyalty_memberships(program_id, status);

-- =====================================================
-- 5. loyalty_earn_events
-- Every earn attempt (valid or invalid) for audit trail.
-- Service-role writes only.
-- =====================================================
create table public.loyalty_earn_events (
  id                          uuid primary key default gen_random_uuid(),
  membership_id               uuid not null references public.loyalty_memberships(id) on delete cascade,
  business_id                 uuid not null references public.business_profiles(id),
  user_wallet_pass_id         text not null,
  earned_at                   timestamptz default now(),
  method                      text not null default 'counter_qr'
                              check (method in ('counter_qr')),
  ip_hash                     text,
  geo_hash                    text,
  valid                       boolean not null default true,
  reason_if_invalid           text
);

comment on table public.loyalty_earn_events
  is 'Every earn attempt logged for audit, fraud detection, and cooldown enforcement. Includes invalid attempts with reasons.';

-- Indexes for cooldown checks and stats
create index idx_loyalty_earn_events_membership_time
  on public.loyalty_earn_events(membership_id, earned_at desc);

create index idx_loyalty_earn_events_business_time
  on public.loyalty_earn_events(business_id, earned_at);

create index idx_loyalty_earn_events_ip
  on public.loyalty_earn_events(ip_hash, earned_at)
  where ip_hash is not null;

-- =====================================================
-- 6. loyalty_redemptions
-- Atomic consume records. Service-role writes only.
-- Redemptions are final -- no reversal from dashboard.
-- =====================================================
create table public.loyalty_redemptions (
  id                          uuid primary key default gen_random_uuid(),
  membership_id               uuid not null references public.loyalty_memberships(id) on delete cascade,
  business_id                 uuid not null references public.business_profiles(id),
  user_wallet_pass_id         text not null,
  reward_description          text not null,
  status                      text not null default 'consumed'
                              check (status in ('consumed', 'expired_display')),
  consumed_at                 timestamptz not null default now(),
  display_expires_at          timestamptz not null,
  stamps_deducted             int not null,
  flagged_at                  timestamptz,
  flagged_reason              text,
  created_at                  timestamptz default now()
);

comment on table public.loyalty_redemptions
  is 'Atomic reward consumption records. Redemptions are final in V1. Business can flag for review but cannot reverse.';

comment on column public.loyalty_redemptions.display_expires_at
  is 'consumed_at + 10 minutes. The live proof screen shows until this time.';

comment on column public.loyalty_redemptions.flagged_at
  is 'Set when business owner flags a redemption for review. Does NOT reverse the redemption.';

-- Indexes
create index idx_loyalty_redemptions_membership
  on public.loyalty_redemptions(membership_id, consumed_at desc);

create index idx_loyalty_redemptions_business
  on public.loyalty_redemptions(business_id, consumed_at desc);

-- =====================================================
-- 7. ENABLE ROW LEVEL SECURITY
-- =====================================================
alter table public.loyalty_programs enable row level security;
alter table public.loyalty_pass_requests enable row level security;
alter table public.loyalty_memberships enable row level security;
alter table public.loyalty_earn_events enable row level security;
alter table public.loyalty_redemptions enable row level security;

-- =====================================================
-- 8. RLS POLICIES: loyalty_programs
-- =====================================================

-- Anyone authenticated can read active programs (for discover, business pages, etc.)
-- Business owner can read all statuses of their own program
create policy "loyalty_programs_select_active_or_owner"
  on public.loyalty_programs
  for select
  to authenticated
  using (
    status = 'active'
    or exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_programs.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- Business owner can create their program
create policy "loyalty_programs_insert_owner"
  on public.loyalty_programs
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_programs.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- Business owner can update their program
create policy "loyalty_programs_update_owner"
  on public.loyalty_programs
  for update
  to authenticated
  using (
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_programs.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_programs.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- =====================================================
-- 9. RLS POLICIES: loyalty_pass_requests
-- =====================================================

-- Business owner can read their own requests
create policy "loyalty_pass_requests_select_owner"
  on public.loyalty_pass_requests
  for select
  to authenticated
  using (
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_pass_requests.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- Business owner can create requests
create policy "loyalty_pass_requests_insert_owner"
  on public.loyalty_pass_requests
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_pass_requests.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- UPDATE is service role only (admin activates/rejects)
-- No authenticated UPDATE policy needed

-- =====================================================
-- 10. RLS POLICIES: loyalty_memberships
-- Users can read their own memberships.
-- Business owners can read memberships for their program.
-- All writes are service role only.
-- =====================================================

create policy "loyalty_memberships_select_own"
  on public.loyalty_memberships
  for select
  to authenticated
  using (
    -- User can see their own memberships
    exists (
      select 1 from public.app_users
      where app_users.wallet_pass_id = loyalty_memberships.user_wallet_pass_id
        and app_users.user_id = (select auth.uid())
    )
    or
    -- Business owner can see memberships for their program
    exists (
      select 1 from public.loyalty_programs
      join public.business_profiles
        on business_profiles.id = loyalty_programs.business_id
      where loyalty_programs.id = loyalty_memberships.program_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- No INSERT, UPDATE, or DELETE policies for authenticated users
-- All membership writes go through API endpoints using service role

-- =====================================================
-- 11. RLS POLICIES: loyalty_earn_events
-- Users can read their own events.
-- Business owners can read events for their business.
-- All writes are service role only.
-- =====================================================

create policy "loyalty_earn_events_select_own_or_business"
  on public.loyalty_earn_events
  for select
  to authenticated
  using (
    exists (
      select 1 from public.app_users
      where app_users.wallet_pass_id = loyalty_earn_events.user_wallet_pass_id
        and app_users.user_id = (select auth.uid())
    )
    or
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_earn_events.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- No INSERT policy for authenticated -- service role only

-- =====================================================
-- 12. RLS POLICIES: loyalty_redemptions
-- Users can read their own redemptions.
-- Business owners can read and flag redemptions.
-- INSERT is service role only (atomic consume).
-- =====================================================

create policy "loyalty_redemptions_select_own_or_business"
  on public.loyalty_redemptions
  for select
  to authenticated
  using (
    exists (
      select 1 from public.app_users
      where app_users.wallet_pass_id = loyalty_redemptions.user_wallet_pass_id
        and app_users.user_id = (select auth.uid())
    )
    or
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_redemptions.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- Business owner can update flagged_at and flagged_reason only
-- (column restriction enforced by API, not RLS)
create policy "loyalty_redemptions_update_flag_business"
  on public.loyalty_redemptions
  for update
  to authenticated
  using (
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_redemptions.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  )
  with check (
    exists (
      select 1 from public.business_profiles
      where business_profiles.id = loyalty_redemptions.business_id
        and business_profiles.user_id = (select auth.uid())
    )
  );

-- No INSERT or DELETE policies for authenticated -- service role only

-- =====================================================
-- 13. COMPLETION
-- =====================================================
do $$
begin
  raise notice 'Loyalty System V1 migration complete. 5 tables created, RLS enabled, date_of_birth added to app_users.';
end $$;
